import type { Prisma, PrismaClient ,BlogLink } from "@prisma/client";
import { BaseService } from "./../base-service";

import { createBlogLink } from "./create-blog-link";
import { getBlogLinkById } from "./get-blog-link-by-id";
import { updateBlogLink } from "./update-blog-link";
import { deleteBlogLink } from "./delete-blog-link";
import { getAllBlogLinks } from "./get-all-blog-links";

interface BlogLinkService {
  createBlogLink(data: Prisma.BlogLinkCreateInput): Promise<BlogLink>;
  getBlogLinkById(id: string): Promise<BlogLink | null>;
  updateBlogLink(id: string, data: Prisma.BlogLinkUpdateInput): Promise<BlogLink>;
  deleteBlogLink(id: string): Promise<BlogLink>;
  getAllBlogLinks(): Promise<BlogLink[]>;
}

export type BlogLinkServiceReturnType<T extends keyof BlogLinkService> = Awaited<
  ReturnType<BlogLinkService[T]>
>;

export class BlogLinkServiceImplementation extends BaseService implements BlogLinkService {
  constructor(prisma: PrismaClient) {
    super(prisma);
  }

  async createBlogLink(data: Prisma.BlogLinkCreateInput) {
    const result = await createBlogLink(this.prisma, data);
    return result;
  }

  async getBlogLinkById(id: string) {
    const result = await getBlogLinkById(this.prisma, id);
    return result;
  }

  async updateBlogLink(id: string, data: Prisma.BlogLinkUpdateInput) {
    const result = await updateBlogLink(this.prisma, id, data);
    return result;
  }

  async deleteBlogLink(id: string) {
    const result = await deleteBlogLink(this.prisma, id);
    return result;
  }

  async getAllBlogLinks() {
    const result = await getAllBlogLinks(this.prisma);
    return result;
  }

  // <AUTO-GENERATED METHODS>

  protected async beforeAction(action: string, data: unknown) {
    super.beforeAction(action, data);
    // Custom logic specific to BlogLinkService
  }

  protected async afterAction(action: string, result: unknown) {
    super.afterAction(action, result);
    // Custom logic specific to BlogLinkService
  }
}



