import type { Prisma, PrismaClient ,BlogContent } from "@prisma/client";
import { BaseService } from "./../base-service";

import { createBlogContent } from "./create-blog-content";
import { getBlogContentById } from "./get-blog-content-by-id";
import { updateBlogContent } from "./update-blog-content";
import { deleteBlogContent } from "./delete-blog-content";
import { getAllBlogContents } from "./get-all-blog-contents";

interface BlogContentService {
  createBlogContent(data: Prisma.BlogContentCreateInput): Promise<BlogContent>;
  getBlogContentById(id: string): Promise<BlogContent | null>;
  updateBlogContent(id: string, data: Prisma.BlogContentUpdateInput): Promise<BlogContent>;
  deleteBlogContent(id: string): Promise<BlogContent>;
  getAllBlogContents(): Promise<BlogContent[]>;
}

export type BlogContentServiceReturnType<T extends keyof BlogContentService> = Awaited<
  ReturnType<BlogContentService[T]>
>;

export class BlogContentServiceImplementation extends BaseService implements BlogContentService {
  constructor(prisma: PrismaClient) {
    super(prisma);
  }

  async createBlogContent(data: Prisma.BlogContentCreateInput) {
    const result = await createBlogContent(this.prisma, data);
    return result;
  }

  async getBlogContentById(id: string) {
    const result = await getBlogContentById(this.prisma, id);
    return result;
  }

  async updateBlogContent(id: string, data: Prisma.BlogContentUpdateInput) {
    const result = await updateBlogContent(this.prisma, id, data);
    return result;
  }

  async deleteBlogContent(id: string) {
    const result = await deleteBlogContent(this.prisma, id);
    return result;
  }

  async getAllBlogContents() {
    const result = await getAllBlogContents(this.prisma);
    return result;
  }

  // <AUTO-GENERATED METHODS>

  protected async beforeAction(action: string, data: unknown) {
    super.beforeAction(action, data);
    // Custom logic specific to BlogContentService
  }

  protected async afterAction(action: string, result: unknown) {
    super.afterAction(action, result);
    // Custom logic specific to BlogContentService
  }
}



