import type { Metadata } from "next";
import "./globals.css";

import ApolloClientProvider from "@/shared/utils/apollo/ApolloProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloClientProvider>
        <body>{children}</body>
      </ApolloClientProvider>
    </html>
  );
}
