import type { Prisma, PrismaClient ,BlogPlaylistItem } from "@prisma/client";
import { BaseService } from "./../base-service";

import { createBlogPlaylistItem } from "./create-blog-playlist-item";
import { getBlogPlaylistItemById } from "./get-blog-playlist-item-by-id";
import { updateBlogPlaylistItem } from "./update-blog-playlist-item";
import { deleteBlogPlaylistItem } from "./delete-blog-playlist-item";
import { getAllBlogPlaylistItems } from "./get-all-blog-playlist-items";

interface BlogPlaylistItemService {
  createBlogPlaylistItem(data: Prisma.BlogPlaylistItemCreateInput): Promise<BlogPlaylistItem>;
  getBlogPlaylistItemById(id: string): Promise<BlogPlaylistItem | null>;
  updateBlogPlaylistItem(id: string, data: Prisma.BlogPlaylistItemUpdateInput): Promise<BlogPlaylistItem>;
  deleteBlogPlaylistItem(id: string): Promise<BlogPlaylistItem>;
  getAllBlogPlaylistItems(): Promise<BlogPlaylistItem[]>;
}

export type BlogPlaylistItemServiceReturnType<T extends keyof BlogPlaylistItemService> = Awaited<
  ReturnType<BlogPlaylistItemService[T]>
>;

export class BlogPlaylistItemServiceImplementation extends BaseService implements BlogPlaylistItemService {
  constructor(prisma: PrismaClient) {
    super(prisma);
  }

  async createBlogPlaylistItem(data: Prisma.BlogPlaylistItemCreateInput) {
    await this.beforeAction("createBlogPlaylistItem", data);
    const result = await createBlogPlaylistItem(this.prisma, data);
    await this.afterAction("reateBlogPlaylistItem", result);
    return result;
  }

  async getBlogPlaylistItemById(id: string) {
    await this.beforeAction("getBlogPlaylistItemById", id);
    const result = await getBlogPlaylistItemById(this.prisma, id);
    await this.afterAction("getBlogPlaylistItemById", result);
    return result;
  }

  async updateBlogPlaylistItem(id: string, data: Prisma.BlogPlaylistItemUpdateInput) {
    await this.beforeAction("updateBlogPlaylistItem", { id, data });
    const result = await updateBlogPlaylistItem(this.prisma, id, data);
    await this.afterAction("updateBlogPlaylistItem", result);
    return result;
  }

  async deleteBlogPlaylistItem(id: string) {
    await this.beforeAction("deleteBlogPlaylistItem", id);
    const result = await deleteBlogPlaylistItem(this.prisma, id);
    await this.afterAction("deleteBlogPlaylistItem", result);
    return result;
  }

  async getAllBlogPlaylistItems() {
    await this.beforeAction("getAllBlogPlaylistItems", null);
    const result = await getAllBlogPlaylistItems(this.prisma);
    await this.afterAction("getAllBlogPlaylistItems", result);
    return result;
  }

  // <AUTO-GENERATED METHODS>

  protected async beforeAction(action: string, data: unknown) {
    super.beforeAction(action, data);
    // Custom logic specific to BlogPlaylistItemService
  }

  protected async afterAction(action: string, result: unknown) {
    super.afterAction(action, result);
    // Custom logic specific to BlogPlaylistItemService
  }
}



